# Generated by Django 5.2.17 on 2026-08-11 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('nazwa', models.CharField(max_length=64)),
                ('prefix', models.CharField(blank=True, help_text='Prefiks kodu ofert, np. n -> n001', max_length=3)),
                ('porzadek', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Kategoria',
                'verbose_name_plural': 'Kategorie',
                'ordering': ['porzadek', 'nazwa'],
            },
        ),
        migrations.CreateModel(
            name='WiadomoscKontakt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('imie', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('wiadomosc', models.TextField()),
                ('przeczytane', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Wiadomość kontakt',
                'verbose_name_plural': 'Wiadomości kontakt',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wojewodztwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(help_text='3-znakowy kod, np. maz, sla', max_length=4, unique=True)),
                ('nazwa', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'Województwo',
                'verbose_name_plural': 'Województwa',
                'ordering': ['nazwa'],
            },
        ),
        migrations.CreateModel(
            name='Ogloszenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_publiczny', models.CharField(blank=True, help_text='Kod oferty (np. n001), generowany automatycznie', max_length=8, unique=True)),
                ('slug', models.SlugField(help_text='Adres oferty, np. syndyk-sprzeda-mieszkanie-lodz', max_length=220, unique=True)),
                ('tytul', models.CharField(max_length=200)),
                ('opis_krotki', models.CharField(blank=True, help_text='Skrót na kartę oferty (opcjonalny)', max_length=280)),
                ('opis', models.TextField(help_text='Treść obwieszczenia (HTML z edytora wizualnego)')),
                ('jak_kupic', models.TextField(blank=True, default='', help_text='Jak przystąpić do zakupu / przetargu (HTML)', verbose_name='Tryb zakupu')),
                ('kontakt', models.TextField(blank=True, default='', help_text='Kontakt w sprawie oferty. Pusty => dane biura')),
                ('cena', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cena_typ', models.CharField(choices=[('brutto', 'brutto'), ('netto', 'netto')], default='brutto', max_length=8)),
                ('cena_tekst', models.CharField(blank=True, help_text='Zastępuje cenę liczbową, np. "najwyższa zaoferowana"', max_length=120)),
                ('wadium', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('miejscowosc', models.CharField(blank=True, max_length=80)),
                ('tryb', models.CharField(choices=[('papierowy', 'Przetarg pisemny'), ('papierowy_elektroniczny', 'Przetarg pisemny / elektroniczny'), ('elektroniczny', 'Przetarg elektroniczny'), ('z_wolnej_reki', 'Sprzedaż z wolnej ręki')], default='papierowy', max_length=32)),
                ('publikacja_od', models.DateTimeField(blank=True, help_text='Puste = widoczne od razu po opublikowaniu', null=True)),
                ('wygasa', models.DateTimeField(blank=True, help_text='Termin składania ofert — napędza odliczanie. Puste = bez terminu', null=True)),
                ('sygnatura', models.CharField(blank=True, help_text='np. XIV GUp 247/24', max_length=32)),
                ('sad', models.CharField(blank=True, max_length=128)),
                ('upadly', models.CharField(blank=True, max_length=160)),
                ('edycja', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('szkic', 'Szkic'), ('opublikowane', 'Opublikowane'), ('zarchiwizowane', 'Zarchiwizowane')], default='szkic', help_text='Szkic = niewidoczne. Opublikowane = widoczne. Zarchiwizowane = zdjęte z listy (link działa z bannerem)', max_length=20)),
                ('liczba_wyswietlen', models.PositiveIntegerField(default=0, editable=False)),
                ('kategoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ogloszenia', to='oferty.kategoria')),
                ('parent', models.ForeignKey(blank=True, help_text='Poprzednia edycja tego samego przetargu', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edycje', to='oferty.ogloszenie')),
                ('wojewodztwo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ogloszenia', to='oferty.wojewodztwo')),
            ],
            options={
                'verbose_name': 'Oferta',
                'verbose_name_plural': 'Oferty',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OgloszenieZdjecie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, upload_to='oferty/')),
                ('img_url', models.URLField(blank=True, help_text='Alternatywnie: URL zdjęcia z zewnątrz')),
                ('plik_watermark', models.ImageField(blank=True, editable=False, upload_to='oferty/watermark/%Y/%m/')),
                ('porzadek', models.PositiveSmallIntegerField(default=0)),
                ('is_glowne', models.BooleanField(default=False, help_text='Zdjęcie główne (na liście, w nagłówku)')),
                ('ogloszenie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zdjecia', to='oferty.ogloszenie')),
            ],
            options={
                'verbose_name': 'Zdjęcie',
                'verbose_name_plural': 'Zdjęcia',
                'ordering': ['porzadek', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Zalacznik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plik', models.FileField(upload_to='oferty/zalaczniki/%Y/%m/')),
                ('nazwa', models.CharField(blank=True, help_text='Pusta => nazwa pliku', max_length=160)),
                ('porzadek', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ogloszenie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zalaczniki', to='oferty.ogloszenie')),
            ],
            options={
                'verbose_name': 'Załącznik',
                'verbose_name_plural': 'Załączniki',
                'ordering': ['porzadek', 'pk'],
            },
        ),
    ]
